language: java
services:
 - mysql
jdk:
 - openjdk7
 - oraclejdk8
 - res jdk6
 - oraclejdk7
branches:
 only:
   - master
   - development
before_install:
 - mysql --user root < /home/travis/build/Warkdev/JaNGOSAuth/database/structure.sql
 - mysql --user root jangosauth < /home/travis/build/Warkdev/JaNGOSAuth/database/data.sql
 
